---
AWSTemplateFormatVersion: '2010-09-09'
Description: MessFinder Database

Parameters:
  deploymentName:
    Type: String
  readCapacity:
    Type: String
    Default: '5'
  writeCapacity:
    Type: String
    Default: '5'

Resources:
  lookupTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: 'objectName'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: 'objectName'
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref readCapacity
        WriteCapacityUnits: !Ref writeCapacity
      TableName: !Join ['', [!Ref deploymentName, '-objects']]


Outputs:
  lookupTableResource:
    Value: !Ref lookupTable
    Export:
      Name: !Sub ${AWS::StackName}-lookupTableResource
